# Generated by Django 5.0.2 on 2024-08-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchNews', '0002_article_pictureurl_article_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pictureUrl',
            field=models.URLField(null=True, unique=True),
        ),
    ]
