# Generated by Django 4.2.5 on 2024-09-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetchNews', '0003_alter_article_pictureurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
